-- COMBINED_APPLY_TO_SUPABASE.sql
-- 
-- This file is superseded by the individual numbered migration files:
--   20260602_messenger_foundation.sql
--   20260605_messenger_schema_fixes.sql
--   20260607000001_retention_analytics.sql
--   20260607000002_signal_functions.sql
--
-- The CI workflow applies those files in sorted order.
-- This stub exists to prevent the old combined content from causing duplicate/broken migrations.
-- Do not add SQL here; add new numbered migration files instead.
