/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUpdatesRouteImport } from './routes/_authenticated/updates'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNewChatRouteImport } from './routes/_authenticated/new-chat'
import { Route as AuthenticatedLoopRouteImport } from './routes/_authenticated/loop'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpdatesRoute = AuthenticatedUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewChatRoute = AuthenticatedNewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoopRoute = AuthenticatedLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/loop': typeof AuthenticatedLoopRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/loop': typeof AuthenticatedLoopRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/loop': typeof AuthenticatedLoopRoute
  '/_authenticated/new-chat': typeof AuthenticatedNewChatRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/calls'
    | '/chats'
    | '/loop'
    | '/new-chat'
    | '/profile'
    | '/updates'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/calls'
    | '/chats'
    | '/loop'
    | '/new-chat'
    | '/profile'
    | '/updates'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/_authenticated/calls'
    | '/_authenticated/chats'
    | '/_authenticated/loop'
    | '/_authenticated/new-chat'
    | '/_authenticated/profile'
    | '/_authenticated/updates'
    | '/_authenticated/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-chat': {
      id: '/_authenticated/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof AuthenticatedNewChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loop': {
      id: '/_authenticated/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof AuthenticatedLoopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedLoopRoute: typeof AuthenticatedLoopRoute
  AuthenticatedNewChatRoute: typeof AuthenticatedNewChatRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUpdatesRoute: typeof AuthenticatedUpdatesRoute
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedLoopRoute: AuthenticatedLoopRoute,
  AuthenticatedNewChatRoute: AuthenticatedNewChatRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUpdatesRoute: AuthenticatedUpdatesRoute,
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
